spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/yourpilling?serverTimezone=Asia/Seoul
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate.format_sql: true

  oauth:
    kakao:
      client-id: cliend-id
      redirect-uri: "http://localhost:8080/login/oauth2/kakao"
      grant_type: authorization_code

  mail:
    host: smtp.naver.com
    port: 465
    username: id
    password: passowrd
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.ssl.trust: smtp.naver.com